### PR TITLE
fix: ensure that the generated Spring XML DSL is valid

### LINKED ISSUE #27: Generated Spring XML DSL is not a valid XML
The generated Spring XML DSL (`src/main/resources/camel-context.xml) is not valid, there is a superfluous `<rest>` opening tag:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://camel.apache.org/schema/spring       http://camel.apache.org/schema/spring/camel-spring.xsd">

    <camelContext xmlns="http://camel.apache.org/schema/spring">

        <onException>
            <exception>java.lang.Exception</exception>
            <handled><constant>true</constant></handled>
            <setHeader headerName="Exchange.HTTP_RESPONSE_CODE">
                <constant>500</constant>
            </setHeader>
            <setBody>
                <simple>${exception.message}</simple>
            </setBody>
        </onException>

        <restConfiguration component="servlet"/>

        <rest path="/" enableCORS="true">
            <get id="openapi.json" produces="application/json" uri="openapi.json">
                <description>Gets the openapi document for this service</description>
                <route>
                    <setBody>
                        <simple>resource:classpath:openapi.json</simple>
                    </setBody>
                </route>
            </get>
        </rest>

        <rest path="/api" bindingMode="json" enableCORS="true">
    
        <rest> <!-- HERE -->
            <get uri="/{id}">
                <description>Fetches task by given identifier</description>
                <param dataType="integer" description="Task identifier" name="id" required="true" type="path"/>
                <to uri="direct:rest1"/>
            </get>
        </rest>

        <route>
            <from uri="direct:rest1"/>
            <to uri="direct:501"/>
        </route>

        <route>
            <from uri="direct:501"/>
            <log message="API operation not yet implemented: ${headers.CamelHttpMethod} ${headers.CamelHttpPath}"/>
            <setHeader headerName="Exchange.HTTP_RESPONSE_CODE">
                <constant>501</constant>
            </setHeader>
            <setBody><simple>API operation not implemented: ${headers.CamelHttpMethod} ${headers.CamelHttpPath}</simple></setBody>
        </route>

    </camelContext>
</beans>
``` 

```

36, 15: cvc-complex-type.2.4.a:  Invalid content was found starting with element 'rest'. One of  '{"http://camel.apache.org/schema/spring":description,  "http://camel.apache.org/schema/spring":verb,  "http://camel.apache.org/schema/spring":delete,  "http://camel.apache.org/schema/spring":get,  "http://camel.apache.org/schema/spring":head,  "http://camel.apache.org/schema/spring":options,  "http://camel.apache.org/schema/spring":patch,  "http://camel.apache.org/schema/spring":post,  "http://camel.apache.org/schema/spring":put}' is expected.
58, 7: The element type "rest" must be terminated by the matching end-tag "</rest>".
```

### PR DESCRIPTION
**Pull request by zregvart**
Fixes #27

### CODE REVIEW

**Comment by zregvart** [comment]
I fixed some formatting issues (`tab` -> `space`), hope that's OK. When reviewing you might want to [ignore whitespace](https://github.com/jboss-fuse/fuse-apicurito-generator/pull/28/files?w=1) changes.

**Comment by bfitzpat** [comment]
Will take a look -- thanks @zregvart !

**Comment by bfitzpat** [comment]
I got some build errors locally with the versions you specified. @cunningt is working on updating the versions more automatically, but has a different set of versions here that seem to work for me locally (https://github.com/jboss-fuse/fuse-apicurito-generator/pull/29). 

But other than that, with local testing -- the project I created with your indent/spaces fixes looks awesome. Thanks for that!!

**Comment by zregvart** [comment]
@bfitzpat I've removed the versions upgrade, the CI job now fails, the version `3.5.33.fuse-720024` of `io.fabric8:fabric8-maven-plugin` [doesn't exist](https://repository.jboss.org/nexus/content/groups/ea/io/fabric8/fabric8-maven-plugin/3.5.33.fuse-720024/) (any more) in [JBoss EA repository](https://repository.jboss.org/nexus/content/groups/ea/org/jboss/redhat-fuse/fabric8-maven-plugin/), a 7.2.x version doesn't seem to exist in the Red Hat GA Maven repository (7.1.x is `3.5.33.fuse-710023-redhat-00002` if I parse the versions right). For 7.3.x there is an early access version (`3.5.33.fuse-730010`).

**Comment by bfitzpat** [comment]
Yup. Sounds about right. Tom is still working on getting the versions to sync up with upstream builds, so we'll get this in as soon as we get that working. Thanks @zregvart !

**Comment by bfitzpat** [comment]
@zregvart If you rebase this PR, I think we can merge it now that https://github.com/jboss-fuse/fuse-apicurito-generator/pull/29 was successfully merged and built. Thanks for the PR!

**Pull request merged**
