### PR TITLE
Remove unused import package from template to generate project (#11)

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
error is not related to my PR:
[ERROR] Failed to execute goal org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720009:resource (fmp) on project fuse-apicurito-generator: Execution fmp of goal org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720009:resource failed: Plugin org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720009 or one of its dependencies could not be resolved: Failed to collect dependencies at org.jboss.redhat-fuse:fabric8-maven-plugin:jar:7.2.0.fuse-720009 -> io.fabric8:fabric8-maven-plugin:jar:3.5.33.fuse-720013: Failed to read artifact descriptor for io.fabric8:fabric8-maven-plugin:jar:3.5.33.fuse-720013: Could not transfer artifact io.fabric8:fabric8-maven-plugin:pom:3.5.33.fuse-720013 from/to jb-eap-7.1-brew (http://download.eng.bos.redhat.com/brewroot/repos/jb-eap-7.1-rhel-7-maven-build/latest/maven): download.eng.bos.redhat.com: Name or service not known: Unknown host download.eng.bos.redhat.com: Name or service not known -> [Help 1]

**Comment by EricWittmann** [comment]
I cannot build this project locally anymore (I haven't tried in awhile).  I get the same (or similar) error:

```
Non-resolvable import POM: Could not transfer artifact org.jboss.redhat-fuse:fuse-springboot-bom:pom:7.2.0.fuse-720009 from/to jb-eap-7.1-brew (http://download.eng.bos.redhat.com/brewroot/repos/jb-eap-7.1-rhel-7-maven-build/latest/maven): download.eng.bos.redhat.com @ line 308, column 16
```

Anyone know where this artifact lives?  There are a bunch of repositories in the pom.xml now - and a non-zero number of them seem to be only available on the VPN...

**Comment by EricWittmann** [comment]
@bfitzpat do you agree?  We can just force-merge this PR.

**Comment by apupier** [comment]
I will rebase on master

**Comment by bfitzpat** [comment]
> 
> 
> @bfitzpat do you agree? We can just force-merge this PR.

It would be better to rebase and update it first, but the changes are VERY minimal in this case.

**Pull request merged**
