### PR TITLE
issue9 - adding IDs to generated fuse project from apicurito generator

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
This PR adds a new test, tweaks the camel file template slightly, and creates UUID-generated for anything generated with the Rest DSL from apicurito.

**Comment by bfitzpat** [comment]
Here's an example generated with the new code:
`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://camel.apache.org/schema/spring       http://camel.apache.org/schema/spring/camel-spring.xsd">

    <camelContext id="context1" xmlns="http://camel.apache.org/schema/spring">

        <onException>
            <exception>java.lang.Exception</exception>
            <handled><constant>true</constant></handled>
            <setHeader headerName="Exchange.HTTP_RESPONSE_CODE">
                <constant>500</constant>
            </setHeader>
            <setBody>
                <simple>${exception.message}</simple>
            </setBody>
        </onException>

        <restConfiguration component="servlet" apiContextPath="/openapi.json"/>

        <rest id="rest1" path="/" enableCORS="true">
            <get id="openapi.json" produces="application/json" uri="openapi.json">
                <description>Gets the openapi document for this service</description>
                <route id="rest1-route1">
                    <setHeader id="setHeader-route1" headerName="Exchange.CONTENT_TYPE">
                        <constant>application/vnd.oai.openapi+json</constant>
                    </setHeader>
                    <setBody id="setBody-route1">
                        <simple>resource:classpath:openapi.json</simple>
                    </setBody>
                </route>
            </get>
        </rest>

        <rest id="rest2" path="" bindingMode="json" enableCORS="true">
            <get uri="/mypath">
                <description>Grab some data from somewhere.</description>
                <to uri="direct:rest1"/>
            </get>
            <put uri="/mypath">
                <description>Put some data somewhere.</description>
                <to uri="direct:rest2"/>
            </put>
        </rest>

        <route id="9cb6d4e1-41f2-46a1-b4e9-e1a9f4029e1d">
            <from id="47ad5e5c-98ac-45aa-a287-e74e375bb0e0" uri="direct:rest1"/>
            <to id="52e11bdf-ff34-4509-8995-77350ded49b8" uri="direct:501"/>
        </route>
        <route id="1423fa87-bfeb-48a9-9954-2135c78a09b6">
            <from id="6616f6a5-ed94-44a1-a2b1-27f17b0ebc2a" uri="direct:rest2"/>
            <to id="f2050b02-625f-403f-b8a3-02c5f5335136" uri="direct:501"/>
        </route>

        <route id="route2">
            <from id="from-route2" uri="direct:501"/>
            <log id="log-route2" message="API operation not yet implemented: ${headers.CamelHttpMethod} ${headers.CamelHttpPath}"/>
            <setHeader id="setHeader-route2" headerName="Exchange.HTTP_RESPONSE_CODE">
                <constant>501</constant>
            </setHeader>
            <setBody id="setBody-route2">
                <simple>API operation not implemented: ${headers.CamelHttpMethod} ${headers.CamelHttpPath}</simple>
            </setBody>
        </route>

    </camelContext>
</beans>
`

**Comment by apupier** [comment]
> I'm not sure what the ID is used for, specifically

In modeling world, there are usually a design id to model elements. It is a good practice to have design ids to be able to link correctly to the source. With Camel, there is no specific design id, the id used is both design and runtime (which can also have its -discussed- advantages, such as validating at design time unicity of these ids, being able to reference elements from a context to another)
Concretely, these ids are used by Fuse Tooling for debugging purpose and also for the internal Camel design model.

**Comment by zregvart** [comment]
@bfitzpat you could also use the underlying Mustache templating framework, it supports simple `Function<String, String>` helpers, like:

```java
Mustache mustache = new DefaultMustacheFactory().compile(new StringReader("Hi I'm an {{uuid}}"), "example");

Function<String, String> uuid = (s) -> UUID.randomUUID().toString();

mustache.execute(new OutputStreamWriter(System.out),
    Collections.singletonList(Collections.singletonMap("uuid", uuid))).flush();
```

Would yield:

```
Hi I'm an 131497df-fe6c-4818-9954-0a0bc3be182d
```

You need to add that `Function<String, String>` to `variables` here:

https://github.com/jboss-fuse/fuse-apicurito-generator/blob/7ba5a8b134f59bce314e4bb917b949060811e503/src/main/java/com/redhat/fuse/apicurio/jaxrs/GenerateFuseProjectResource.java#L123-L127

**Comment by bfitzpat** [comment]
@zregvart That's MUCH cleaner -- thanks for the great suggestion!

**Comment by bfitzpat** [comment]
@EricWittmann or @apupier can you take another look for approval?

**Pull request merged**
